### Create new user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "asdf@gh.com",
    "password": "sdfsdfd",
    "extrawhitelist": "not_responsible"
}


### Find user
GET http://localhost:3000/auth/121212


### Find all users
GET http://localhost:3000/auth?email=asdf@gh.com

### Delete user
DELETE http://localhost:3000/auth/1

### update user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "asdfffffffffffff@gh.com"
}
